// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Lab4_SvmClassification
{
    public partial class LolGoldStatsData
    {
        /// <summary>
        /// model input class for LolGoldStatsData.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"KDA")]
            public float KDA { get; set; }

            [ColumnName(@"CSPERMIN")]
            public float CSPERMIN { get; set; }

            [ColumnName(@"GOLDINMIN15")]
            public float GOLDINMIN15 { get; set; }

            [ColumnName(@"GOLDIN30MIN")]
            public float GOLDIN30MIN { get; set; }

            [ColumnName(@"RATING")]
            public string RATING { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for LolGoldStatsData.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public string Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@".\SvmClassification\LolGoldStats\LolGoldStatsData.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
