// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Lab4_SvmClassification
{
    public partial class BanknoteData
    {
        /// <summary>
        /// model input class for BanknoteData.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Variance")]
            public float Variance { get; set; }

            [ColumnName(@"Skewness")]
            public float Skewness { get; set; }

            [ColumnName(@"Kurtosis")]
            public float Kurtosis { get; set; }

            [ColumnName(@"Entropy")]
            public float Entropy { get; set; }

            [ColumnName(@"Class")]
            public float Class { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for BanknoteData.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public float Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@".\SvmClassification\Banknote\BanknoteData.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
